//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_2_по_ТРПО_Сервис_частных_объявлений
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public double ad_id { get; set; }
        public Nullable<double> user_id { get; set; }
        public string ad_title { get; set; }
        public string ad_description { get; set; }
        public Nullable<System.DateTime> ad_post_date { get; set; }
        public Nullable<double> city_id { get; set; }
        public Nullable<double> category_id { get; set; }
        public Nullable<double> ad_type_id { get; set; }
        public Nullable<double> ad_status_id { get; set; }
        public Nullable<double> price { get; set; }
        public string ad_photo_path { get; set; }
    
        public virtual Ad_Statuses Ad_Statuses { get; set; }
        public virtual Ad_Types Ad_Types { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Users Users { get; set; }
    }
}
